//
//  Units.swift
//  Units
//
//  Created by Todd Papke on 10/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


protocol Units {
    init?(json: [String: Any]?)
    init()
    init?(data: Data?)
    func jsonDictionary() -> [String: Any]
}



