//
//  Unitinfo.swift
//  Units
//
//  Created by Todd Papke on 10/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct Unitinfo: Units {
    var Unit_Data_ID: Int
    var Unit_Name: String


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        Unit_Data_ID = json["Unit_Data_ID"] as? Int ?? 0
        Unit_Name = json["Unit_Name"] as? String ?? ""
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(Unit_Data_ID: Int, Unit_Name: String) {
        self.Unit_Data_ID = Unit_Data_ID
        self.Unit_Name = Unit_Name
    }



    func jsonDictionary() -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["Unit_Data_ID"] = Unit_Data_ID
        dict["Unit_Name"] = Unit_Name
        return dict
    }



}



