//
//  Root.swift
//  PressureUlcers
//
//  Created by Todd Papke on 09/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct Root: PatientDetail {
    var Pat_Name: String
    var Age_Sex: String
    var Ulcer_Info: [Ulcer_info]
    var MRN: String
    var Survey_Status_Code: String
    var Survey_ID: Int
    var IsBeingEdited: Bool
    var Unit_Data_ID: Int
    var Visited_OR_this_Admission: Bool
    var Room_Bed: String


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        Pat_Name = json["Pat_Name"] as? String ?? ""
        Age_Sex = json["Age_Sex"] as? String ?? ""
        Ulcer_Info = (json["Ulcer_Info"] as? [[String: Any]] ?? []).flatMap{Ulcer_info(json: $0)}
        MRN = json["MRN"] as? String ?? ""
        Survey_Status_Code = json["Survey_Status_Code"] as? String ?? ""
        Survey_ID = json["Survey_ID"] as? Int ?? 0
        IsBeingEdited = json["IsBeingEdited"] as? Bool ?? false
        Unit_Data_ID = json["Unit_Data_ID"] as? Int ?? 0
        Visited_OR_this_Admission = json["Visited_OR_this_Admission"] as? Bool ?? false
        Room_Bed = json["Room_Bed"] as? String ?? ""
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(Pat_Name: String, Age_Sex: String, Ulcer_Info: [Ulcer_info], MRN: String, Survey_Status_Code: String, Survey_ID: Int, IsBeingEdited: Bool, Unit_Data_ID: Int, Visited_OR_this_Admission: Bool, Room_Bed: String) {
        self.Pat_Name = Pat_Name
        self.Age_Sex = Age_Sex
        self.Ulcer_Info = Ulcer_Info
        self.MRN = MRN
        self.Survey_Status_Code = Survey_Status_Code
        self.Survey_ID = Survey_ID
        self.IsBeingEdited = IsBeingEdited
        self.Unit_Data_ID = Unit_Data_ID
        self.Visited_OR_this_Admission = Visited_OR_this_Admission
        self.Room_Bed = Room_Bed
    }



    func jsonDictionary() -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["Pat_Name"] = Pat_Name
        dict["Age_Sex"] = Age_Sex
        dict["Ulcer_Info"] = Ulcer_Info.map{$0.jsonDictionary()}
        dict["MRN"] = MRN
        dict["Survey_Status_Code"] = Survey_Status_Code
        dict["Survey_ID"] = Survey_ID
        dict["IsBeingEdited"] = IsBeingEdited
        dict["Unit_Data_ID"] = Unit_Data_ID
        dict["Visited_OR_this_Admission"] = Visited_OR_this_Admission
        dict["Room_Bed"] = Room_Bed
        return dict
    }



}



