//
//  PatientSummary.swift
//  PatientSummary
//
//  Created by Todd Papke on 10/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


protocol PatientSummary {
    init?(json: [String: Any]?)
    init()
    init?(data: Data?)
    func jsonDictionary() -> [String: Any]
}



