//
//  Root.swift
//  Patient_Summary
//
//  Created by Todd Papke on 10/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct Root: Patient_Summary {
    var Patient_Summary: [Patient_summary]


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        Patient_Summary = (json["Patient_Summary"] as? [[String: Any]] ?? []).flatMap{Patient_summary(json: $0)}
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(Patient_Summary: [Patient_summary]) {
        self.Patient_Summary = Patient_Summary
    }



    func jsonDictionary() -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["Patient_Summary"] = Patient_Summary.map{$0.jsonDictionary()}
        return dict
    }



}



