//
//  JSONCompatible.swift
//  PressureUlcer
//
//  Created by Todd Papke on 11/09/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


protocol JSONCompatible {
    init?(json: [String: Any]?)
    init()
    init?(data: Data?)
    func jsonDictionary() -> [String: Any]
}



