//
//  Root.swift
//  PressureUlcers
//
//  Created by Todd Papke on 09/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct Root: UnitNames {
    var UnitInfo: [Unitinfo]


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        UnitInfo = (json["UnitInfo"] as? [[String: Any]] ?? []).flatMap{Unitinfo(json: $0)}
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(UnitInfo: [Unitinfo]) {
        self.UnitInfo = UnitInfo
    }



    func jsonDictionary() -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["UnitInfo"] = UnitInfo.map{$0.jsonDictionary()}
        return dict
    }



}



