//
//  PatientDetail.swift
//  PressureUlcers
//
//  Created by Todd Papke on 09/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


protocol PatientDetail {
    init?(json: [String: Any]?)
    init()
    init?(data: Data?)
    func jsonDictionary() -> [String: Any]
}



