//
//  Patient_summary.swift
//  PatientSummary
//
//  Created by Todd Papke on 09/10/17.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


protocol Patient_summary {
    init?(json: [String: Any]?)
    init()
    init?(data: Data?)
    func jsonDictionary() -> [String: Any]
}



